version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.5
  aws-cli: circleci/aws-cli@0.1.6

_defaults: &defaults
  machine:
    docker_layer_caching: false
  working_directory: ~/repo
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3000m
    SBT_OPTS: -Xmx2000m
    TERM: dumb

workflows:
  version: 2
  development:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish-snapshot:
          context: nexus
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - publish:
          context: nexus
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.sbt" }}
            - v2-dependencies-
      - run:
          name: Download and run Nomad
          command: >
            cat /etc/os-release && \ 
            curl -O https://releases.hashicorp.com/nomad/0.11.3/nomad_0.11.3_linux_amd64.zip && \
            unzip nomad_0.11.3_linux_amd64.zip && \
            ./nomad agent --dev
      - run:
          name: Compile
          command: cat /dev/null | sbt +validate
      - save_cache:
          paths:
            - ~/.cache/coursier
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.sbt
            - target
          key: v2-dependencies-{{ checksum "build.sbt" }}

  publish:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Release version and bump snapshot
        command: cat /dev/null | sbt ci-release


  publish-snapshot:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        - v1-dependencies-

    - run:
        name: Release version and bump snapshot
        command: cat /dev/null | sbt ci-release